//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PharmacyClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Receipts
    {
        public int R_ID { get; set; }
        public int R_DRUG { get; set; }
        public int R_SUPPLIER { get; set; }
        public int R_AMOUNT { get; set; }
        public System.DateTime R_DATE { get; set; }
        public double R_PRICE { get; set; }
    
        public virtual Drugs Drugs { get; set; }
        public virtual Suppliers Suppliers { get; set; }
    }
}
