//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PharmacyClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales
    {
        public int SAL_ID { get; set; }
        public int SAL_DRUG { get; set; }
        public int SAL_AMOUNT { get; set; }
        public System.DateTime SAL_DATE { get; set; }
        public double SAL_COST { get; set; }
    
        public virtual Drugs Drugs { get; set; }
    }
}
