//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PharmacyClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Storage
    {
        public int ST_ID { get; set; }
        public int ST_DRUG { get; set; }
        public System.DateTime ST_DATE { get; set; }
        public int ST_AMOUNT { get; set; }
    
        public virtual Drugs Drugs { get; set; }
    }
}
